version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "05:00"
    assignees:
      - "marvinvanaalst"
    commit-message:
      prefix: "build(deps): "
    groups:
      dependencies:
        patterns:
          - "*"
